### PR TITLE
Websocket module

### PR DESCRIPTION
**Pull request by litterbear**
Hi, Mentors @lmesz @juhaszviktor 

The [websocket proposal](https://github.com/balabit/syslog-ng/wiki/GSoC-2016-Proposal:-WebSocket-for-syslog-ng-(Yilin-Li)#goals-for-the-project) will be implemented here

Please feel free to point my mistakes.
Thanks :) !!

### CODE REVIEW

**Comment by litterbear** [comment]
I just commit the skeleton for the destination which will do nothing currently

**Comment by juhaszviktor** [comment]
Thanks for contribution,
This is looks good, except the gitignore modifications.

Can you drop the gitignore modifications?
I'm going to create a websocket-module branch. Because this is a skeleton, I suggest, that send your pull request to this (websocket-module) branch.

**Comment by juhaszviktor** [comment]
@litterbear can you send these commits to the websocket-module branch?
It exists, now.

Thanks

**Comment by litterbear** [comment]
@juhaszviktor  
Thanks for reviewing
I've created the #156  PR to the branch you created. :)

What's wrong with my .gitignore file?

**Comment by litterbear** [comment]
Oh, I see  what's wrong with my .gitignorew now.  Thanks for  replying in #154

**Comment by lmesz** [comment]
I think, because of the new PR it would be great to close this issue to not confuse people who wants to follow the progress of your works.
So please @litterbear close this issue!

**Comment by litterbear** [comment]
I see now.  OK :)

**Pull request closed without merging**
